# Generated by Django 3.0.5 on 2020-04-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('updationdate', models.CharField(db_column='updationDate', max_length=255)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorspecialization', models.CharField(blank=True, db_column='doctorSpecialization', max_length=255, null=True)),
                ('doctorid', models.IntegerField(blank=True, db_column='doctorId', null=True)),
                ('userid', models.IntegerField(blank=True, db_column='userId', null=True)),
                ('consultancyfees', models.IntegerField(blank=True, db_column='consultancyFees', null=True)),
                ('appointmentdate', models.CharField(blank=True, db_column='appointmentDate', max_length=255, null=True)),
                ('appointmenttime', models.CharField(blank=True, db_column='appointmentTime', max_length=255, null=True)),
                ('postingdate', models.DateTimeField(blank=True, db_column='postingDate', null=True)),
                ('userstatus', models.IntegerField(blank=True, db_column='userStatus', null=True)),
                ('doctorstatus', models.IntegerField(blank=True, db_column='doctorStatus', null=True)),
                ('updationdate', models.DateTimeField(blank=True, db_column='updationDate', null=True)),
                ('doc_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specilization', models.CharField(blank=True, max_length=255, null=True)),
                ('doctorname', models.CharField(blank=True, db_column='doctorName', max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('docfees', models.CharField(blank=True, db_column='docFees', max_length=255, null=True)),
                ('contactno', models.BigIntegerField(blank=True, null=True)),
                ('docemail', models.CharField(blank=True, db_column='docEmail', max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('creationdate', models.DateTimeField(blank=True, db_column='creationDate', null=True)),
                ('updationdate', models.DateTimeField(blank=True, db_column='updationDate', null=True)),
            ],
            options={
                'db_table': 'doctors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctorslog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('userip', models.CharField(blank=True, max_length=16, null=True)),
                ('logintime', models.DateTimeField(blank=True, db_column='loginTime', null=True)),
                ('logout', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doctorslog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctorspecilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specilization', models.CharField(blank=True, max_length=255, null=True)),
                ('creationdate', models.DateTimeField(blank=True, db_column='creationDate', null=True)),
                ('updationdate', models.DateTimeField(blank=True, db_column='updationDate', null=True)),
            ],
            options={
                'db_table': 'doctorspecilization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcontactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('contactno', models.BigIntegerField(blank=True, null=True)),
                ('msg_subject', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('postingdate', models.DateTimeField(blank=True, db_column='PostingDate', null=True)),
                ('adminremark', models.TextField(blank=True, db_column='AdminRemark', null=True)),
                ('lastupdationdate', models.DateTimeField(blank=True, db_column='LastupdationDate', null=True)),
                ('isread', models.IntegerField(blank=True, db_column='IsRead', null=True)),
            ],
            options={
                'db_table': 'tblcontactus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblmedicalhistory',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('patientid', models.IntegerField(blank=True, db_column='PatientID', null=True)),
                ('bloodpressure', models.CharField(blank=True, db_column='BloodPressure', max_length=200, null=True)),
                ('bloodsugar', models.CharField(db_column='BloodSugar', max_length=200)),
                ('weight', models.CharField(blank=True, db_column='Weight', max_length=100, null=True)),
                ('temperature', models.CharField(blank=True, db_column='Temperature', max_length=200, null=True)),
                ('medicalpres', models.TextField(blank=True, db_column='MedicalPres', null=True)),
                ('creationdate', models.DateTimeField(db_column='CreationDate')),
            ],
            options={
                'db_table': 'tblmedicalhistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblpatient',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('docid', models.IntegerField(blank=True, db_column='Docid', null=True)),
                ('patientname', models.CharField(blank=True, db_column='PatientName', max_length=200, null=True)),
                ('patientcontno', models.BigIntegerField(blank=True, db_column='PatientContno', null=True)),
                ('patientemail', models.CharField(blank=True, db_column='PatientEmail', max_length=200, null=True)),
                ('patientgender', models.CharField(blank=True, db_column='PatientGender', max_length=50, null=True)),
                ('patientadd', models.TextField(blank=True, db_column='PatientAdd', null=True)),
                ('patientage', models.IntegerField(blank=True, db_column='PatientAge', null=True)),
                ('patientmedhis', models.TextField(blank=True, db_column='PatientMedhis', null=True)),
                ('creationdate', models.DateTimeField(blank=True, db_column='CreationDate', null=True)),
                ('updationdate', models.DateTimeField(blank=True, db_column='UpdationDate', null=True)),
            ],
            options={
                'db_table': 'tblpatient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('userip', models.CharField(blank=True, max_length=16, null=True)),
                ('logintime', models.DateTimeField(blank=True, db_column='loginTime', null=True)),
                ('logout', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'userlog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=255, null=True)),
                ('lastname', models.TextField(db_column='lastName')),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('regdate', models.DateTimeField(blank=True, db_column='regDate', null=True)),
                ('updationdate', models.DateTimeField(blank=True, db_column='updationDate', null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
