# Generated by Django 3.0.5 on 2020-05-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
