# Generated by Django 3.0.5 on 2020-05-03 20:14

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management_system', '0003_auto_20200502_2136'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='doctors',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastname',
            field=models.CharField(blank=True, db_column='lastName', max_length=255, null=True),
        ),
    ]
