# Generated by Django 3.0.5 on 2020-05-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management_system', '0004_auto_20200503_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='docemail',
            field=models.CharField(blank=True, db_column='docEmail', max_length=255, null=True, unique=True),
        ),
    ]
