# Generated by Django 3.0.5 on 2020-05-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management_system', '0006_remove_users_is_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='doctors',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='docemail',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='id',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='password',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='specilization',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='updationdate',
        ),
        migrations.AddField(
            model_name='doctors',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialization',
            field=models.CharField(blank=True, default='Doc', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='users_ptr',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
