# Generated by Django 3.0.5 on 2020-05-06 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management_system', '0008_auto_20200506_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='creationdate',
            field=models.DateTimeField(blank=True, db_column='creationDate', default=datetime.datetime(2020, 5, 6, 22, 43, 0, 908269), null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='regdate',
            field=models.DateTimeField(blank=True, db_column='regDate', default=datetime.datetime(2020, 5, 6, 22, 43, 0, 907020), null=True),
        ),
    ]
