# Generated by Django 3.0.5 on 2020-05-06 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management_system', '0009_auto_20200506_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='creationdate',
            field=models.DateTimeField(blank=True, db_column='creationDate', default=datetime.datetime(2020, 5, 6, 22, 44, 33, 293194), null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='regdate',
            field=models.DateTimeField(blank=True, db_column='regDate', default=datetime.datetime(2020, 5, 6, 22, 44, 33, 291823), null=True),
        ),
    ]
